### ISSUE TITLE
Compilation errors in TypeScript projects

### ISSUE THREAD

**Issue by jdomizz** [folz/hydra-ts#6]
Hello,

I have used **hydra-ts** in JavaScript projects without problems, but when I try to use it with TypeScript I get typing errors coming from `generateGlsl`, `shaderString` and `addTransformChainMethod` functions.

Could you tell me what is the right configuration for the TypeScript compiler to bypass those errors?

[Here](https://github.com/jdomizz/hydra-ts/commit/965a4e4e10e3abde307963da9f87bdd86af66b91) you can see the specific lines that gave me problems and how I _fixed_ it.

Thanks for your work 💯

**Comment by folz** [comment]
Appreciate the report! Those errors are accurate - I haven't fully typed that file yet.

I intend to figure out types for these files at some point but I don't have a timeline for this. I'm also open to a PR fixing the types, but I ask that it's not suppressed with `as any` or `@ts-ignore`, as there ought to be narrower types for those functions.

Typescript should still produce a build even if there are type errors, so I don't think I've had to do anything specific to cause it to bypass these errors. I agree that generally you'd want to fail CI if there are type issues, but my personal projects using this library aren't at a state where I have CI set up.

**Comment by jdomizz** [comment]
Thank you for your answer!

I agree that `as any` is not an acceptable solution and I understand that, as a developer, you keep those warnings until you have time to approach them.

Even though `tsc` emits code, those errors might intimidate a first-time TypeScript programmer.

[I did some research](https://codeburst.io/what-really-gets-packaged-f2b49397c2a5) and it is possible to set the contents of the `npm` package through the `files` property in `package.json` .  Setting it to `[ "dist", "!dist/jest*" ]` seems to solve the problem.  If you don't see downsides with this approach I can make a PR with the changes (or you can make them yourself when you have time).

By the way, with a `postinstall` task in `npm` that deletes the problematic files you can use the package in a CI/CD process. In fact, this is how I solved the problem initially.

I close the issue since the question is answered.

**Comment by folz** [comment]
Reopening as I've changed my mind from someone else asking about this exact issue. I agree it doesn't make sense to expose these internal TS errors to downstream consumers. Thanks for making the case.
